# Generated by Django 5.2 on 2025-05-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_end_date_alter_user_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='label',
        ),
        migrations.AddField(
            model_name='preference',
            name='culture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preference',
            name='events',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preference',
            name='food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preference',
            name='green_travel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preference',
            name='outdoors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preference',
            name='weather',
            field=models.IntegerField(default=0),
        ),
    ]
